require.context("./img/", true, /\.(png|jpg|gif)$/);
require.context("./icons/", true, /\.svg$/);
import "./css/style.css";
import $ from 'jquery';
import "../plugins/jQuery/slider.js";
import "../plugins/jQuery/slick.min.js";
import toggleMenu from "./modules/toggleMenu";
import smoothScroll from "./modules/smoothScroll";
import makeGallery from "./modules/makeGallery";
import showCards from "./modules/showCards";
import validation from "./modules/validation";
import showReviews from "./modules/showReviews";
import "../plugins/yandex maps/map.js";

toggleMenu();
smoothScroll();
makeGallery();
showCards();
validation();
showReviews();
